import axios from 'axios';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';

import styles from '../styles/home.module.css';

import Contacts from './components/Contacts/Contacts';
import Header from './components/Header';
import Locations from './components/Locations/Locations';
import Slider from './components/Slider/Slider';

const Home: NextPage = () => {
  const [photos, setPhotos] = useState<PhotoProps[]>([{
    albumId: 0,
    id: 0,
    title: '',
    url: '',
    thumbnailUrl: ''
  }]);
  const fetchData = async () => {
    const response = await axios.get('api/photos?ratio=1130x670');
    const data: DataPhotoProps = response.data;
    setPhotos(data.photos);
    console.log(data);
  };

  useEffect( () => {
    fetchData();
  },[]);
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Go Beyond 2021 - Final Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link rel="preload" href="/fonts/Circular-Std/Circular-Std.ttf" as="font" crossOrigin=""/> */}
      </Head>
      <div className={styles.header}>
        <Header />
      </div>
      <div className={styles.slider}>
        <Slider photos={photos}/>
      </div>
      <div className={styles.contacts}>
        <Contacts/>
      </div>
      <div className={styles.locations}>
        <Locations/>
      </div>
    </div>
  )
}

export default Home
